---
galaxy_info:
  role_name: vsftpd
  author: xat59
  description: Install and configure vsftpd FTP server.
  license: LGPLv3
  min_ansible_version: 2.0
  platforms:
    - name: EL
      version:
        - 7
        - 8
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial
  galaxy_tags:
    - ftp
    - ftps
dependencies: []
