- hosts: localhost
  connection: local
  become: true
  gather_facts: no

  vars:
    ftpUser: "ftp"
    ftpPass: "ftp"
    ftpUserRoot: "/var/www/web"

  tasks:
    - name: Instalar paquetes requeridos
      apt:
        pkg:
          - vsftpd
          - libpam-pwdfile
          - apache2
        update_cache: yes
        state: present

    - name: Instalar bcrypt-tool via snap
      snap:
        name: bcrypt-tool
        state: present

    - name: Crear configuraci칩n de vsftpd
      template:
        src: "vsftpd.conf.j2"
        dest: "/etc/vsftpd.conf"

    - name: Crear usuario vsftpd
      user:
        name: vsftpd
        home: /home/vsftpd
        group: nogroup
        shell: /bin/false
        create_home: yes
        system: yes

    - name: Configurar permisos de usuario virtual
      file:
        path: "{{ ftpUserRoot }}"
        state: directory
        owner: vsftpd
        group: nogroup
        mode: '0755'
        recurse: yes

    - name: Crear directorio de configuraci칩n de usuarios
      file:
        path: /etc/vsftpd/userconfig
        state: directory
        mode: '0755'

    - name: Configurar usuario virtual
      blockinfile:
        path: /etc/vsftpd/userconfig/{{ ftpUser }}
        create: yes
        block: |
          local_root={{ ftpUserRoot }}

    - name: Configurar autenticaci칩n PAM
      copy:
        dest: /etc/pam.d/vsftpd
        content: |
          auth required pam_pwdfile.so pwdfile /etc/vsftpd/ftpd.passwd
          account required pam_permit.so

    - name: Crear contrase침a de usuario
      shell: >
        htpasswd -c -p -b /etc/vsftpd/ftpd.passwd {{ ftpUser }}
        $(bcrypt-tool hash {{ ftpPass }})
      # args:
      #   warn: false  # Desactiva la advertencia de uso de comandos

    - name: Generar certificado SSL
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /etc/ssl/private/vsftpd.pem
        -out /etc/ssl/private/vsftpd.pem
        -subj "/CN=localhost"
      args:
        creates: /etc/ssl/private/vsftpd.pem

    - name: Habilitar y reiniciar vsftpd
      service:
        name: vsftpd
        enabled: yes
        state: restarted
