---
- hosts: all
  become: true
  gather_facts: no
  vars:
    ftp_user: "ftpvirtual"
    ftp_group: "ftpgroup"
    vsftpd_conf: "/etc/vsftpd.conf"
    pam_vsftpd: "/etc/pam.d/vsftpd.virtual"
    db_file: "/etc/vsftpd/virtual_users.db"
    users:
      - { name: "usuario1", password: "password1" }
      - { name: "usuario2", password: "password2" }
  tasks:
    - name: Instalar paquetes necesarios
      apt:
        name:
          - vsftpd
          - db-util
          - libpam-pwdfile
        state: present
        update_cache: yes

    #- name: Verificar si la copia ya existe
    #  stat:
    #    path: /etc/vsftpd.conf.bck
    #  register: vsftpd
    #  tags: [ ftp ]

    - name: Copiar archivo si no existe
      copy:
        src: /etc/vsftpd.conf
        dest: /etc/vsftpd.conf.bck
        remote_src: yes  # Indica que el archivo fuente está en el host remoto
   #   when: not vsftpd.stat.exists
   #   tags: [ ftp ]

    - name: Crear grupo para usuarios virtuales
      group:
        name: "{{ ftp_group }}"
        state: present

    - name: Crear usuario del sistema para FTP
      user:
        name: "{{ ftp_user }}"
        group: "{{ ftp_group }}"
        home: "/home/{{ ftp_user }}"
        shell: "/usr/sbin/nologin"
        create_home: yes

    - name: Crear directorio de chroot para los usuarios
      file:
        path: "/home/{{ ftp_user }}/{{ item.name }}"
        state: directory
        owner: "{{ ftp_user }}"
        group: "{{ ftp_group }}"
        mode: '0755'
      loop: "{{ users }}"

    - name: Crear directorio /etc/vsftpd
      file:
        path: "/etc/vsftpd"
        state: directory
        owner: "root"
        group: "root"
        mode: '0755'

    - name: Crear archivo de credenciales para usuarios virtuales
      copy:
        dest: "/etc/vsftpd/virtual_users.txt"
        content: |
          {% for user in users %}
          {{ user.name }}
          {{ user.password }}
          {% endfor %}

    - name: Generar base de datos de usuarios virtuales
      command: db_load -T -t hash -f /etc/vsftpd/virtual_users.txt "{{ db_file }}"
      args:
        creates: "{{ db_file }}"

    - name: Establecer permisos correctos en la base de datos
      file:
        path: "{{ db_file }}"
        owner: root
        group: root
        mode: '0600'

    - name: Configurar autenticación PAM para vsftpd
      copy:
        dest: "{{ pam_vsftpd }}"
        content: |
          auth required pam_pwdfile.so pwdfile={{ db_file }}
          account required pam_permit.so

    - name: Configurar vsftpd
      copy:
        dest: "{{ vsftpd_conf }}"
        content: |
          listen=YES
          anonymous_enable=NO
          local_enable=YES
          write_enable=YES
          local_umask=022
          chroot_local_user=YES
          guest_enable=YES
          guest_username={{ ftp_user }}
          user_sub_token=$USER
          local_root=/home/{{ ftp_user }}/$USER
          hide_ids=YES
          virtual_use_local_privs=YES
          pam_service_name=vsftpd.virtual
          pasv_enable=YES
          pasv_min_port=40000
          pasv_max_port=50000
          allow_writeable_chroot=YES

    - name: Reiniciar vsftpd
      systemd:
        name: vsftpd
        state: restarted
        enabled: yes
